Remove djsonb dependency and move its relevant logic into Grout core
azavea/grout pull request #7
Opened 2018-07-23 19:03 UTC by jeancochrane

# Overview

Now that JSONB is supported in Django core, we no longer need most of the [custom `djsonb` package](https://github.com/azavea/djsonb).This PR removes the external dependency on `djsonb` and moves its lookup logic into Grout core. It also moves the `djsonb` test suite into this package in order to confirm that JSON filtering logic works.

## Notes

- I had to make a few small changes to the `djsonb` lookup logic in order to get it to work with Django's built-in JSONField type. Since those changes won't show up in this diff, [I opened a separate PR over in `djsonb`](https://github.com/azavea/djsonb/pull/16) in order to expose the diff.
- The Lookup module is the only part of `djsonb` that we need to preserve, since it provides all of the logic that parses a query in the format that the Grout API expects (like `jsonb={'a': {'b': {'c': {'_rule_type': 'containment', 'contains': [1, 2]}}}}`) and turns it into SQL.
    - Note that by using the old lookup logic, we're not yet leveraging the main advantage of Django's JSONField type, which is the [built-in query syntax](https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#querying-jsonfield). I didn't want to change the query syntax in this PR, however, since that feels like part of https://github.com/azavea/grout-2018-fellowship/issues/16.
- We had chatted in standup about whether it would be a better idea to update `djsonb` or bring the relevant portions into this package. Since all I need to preserve of `djsonb` is the lookup logic, I decided it would be best to bring it in here.

## Testing

Travis will run unit tests. To run them locally:

```bash
# Update containers.
./scripts/update

# Run tests.
./scripts/test
```

Closes https://github.com/azavea/grout-2018-fellowship/issues/12.

2018-07-23 19:47 UTC, flibbertigibbet requested changes
Looks like the migrations could use a little cleanup. On running the test script:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0024_auto_20180716_1605, 0023_auto_20180717_1003 in grout).```

2018-07-23 20:03 UTC, jeancochrane commented
I don't see the migration labeled `0023_auto_20180717_1003` anywhere [in the `migrations` folder](https://github.com/azavea/grout/tree/remove-djsonb/grout/migrations) in this branch. Any chance it's a holdover from another branch @flibbertigibbet?

2018-07-23 20:06 UTC, flibbertigibbet commented
Sure enough, I guess that one came from the `remove-location-fields` branch :+1:

2018-07-24 13:30 UTC, flibbertigibbet approved these changes
:confetti_ball: 

Just a few notes. I've run the tests locally, but haven't tested it otherwise. Looking forward to seeing this all come together!

2018-07-24 13:30 UTC, flibbertigibbet commented on CHANGELOG.md
> +  Grout core ([#7](https://github.com/azavea/grout/pull/7)
:fireworks:

2018-07-24 13:30 UTC, flibbertigibbet commented on grout/lookups.py
> +    """This class should properly assemble the pieces necessary to write the WHERE clause of
Nitpick: could this block comment be rephrased to open with a single line, separated from the rest with a blank line, [per the docstring PEP](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)?

2018-07-24 13:30 UTC, flibbertigibbet commented on grout/lookups.py
> +            if not self.is_rule(rule[1]):
How do we know index 1 will be in bounds for `rule`? Could it be made more obvious what data is at the 0 and 1 offsets?

2018-07-24 13:30 UTC, flibbertigibbet commented on grout/lookups.py
> +        template = reconstruct_object(path[1:])
Similar to the questions about `rule` above, could it be made more obvious what the slices of `path` contain, and why it's safe to assume `path` has a length of at least two?

2018-07-24 19:24 UTC, jeancochrane commented on grout/lookups.py
> +    """This class should properly assemble the pieces necessary to write the WHERE clause of
Can do. I'll flesh out all the docstrings in this module.

2018-07-24 19:24 UTC, jeancochrane commented on grout/lookups.py
> +            if not self.is_rule(rule[1]):
Great question! Based on the parameter list for the methods that use these values (like `FilterTree.containment_filter`), it looks like `rule[0]` corresponds to the path of the nested query, while `rule[1]` corresponds to the rule itself. Both elements have to exist, since `self.get_rules` can only return either A) an empty list or B) a list of two-tuples.

I'll add this info in a comment and redo the iteration assignment to change it from:

```python
for rule in self.rules:
```

To something more expressive;

```python
for path, rule in self.rules:
```

2018-07-24 19:31 UTC, merged